### ISSUE TITLE
how to crop multi face in one picture？how to define face_num and use it?

### ISSUE THREAD

**Issue by ziyuwzf** [urbaneman/Face_crop_align_mtcnn#2]

**Comment by urbaneman** [comment]
@ziyuwzf Sorry about answer too late. 
In this project, I just make the way to crop one face, if you want crop more than one face, you should add a loop in mtcnn's result, than use the num id and image's name as the face name.

**Comment by urbaneman** [comment]
@ziyuwzf I had update for multi-face crop.
